server:
  port: 8080

springdoc:
  use-management-port: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui

---
spring:
  config:
    activate:
      on-profile: dev

products:
  prefix: "[Sample] "
