logging:

  level:
    root: ERROR
    eshop-dao: DEBUG
    eshop-controller: INFO
    eshop: INFO

  group:
    spring: "org.springframework, org.springdoc"
    eshop-dao: "com.saggu.eshop.dao"
    eshop-controller: "com.saggu.eshop.controller"
    eshop: "com.saggu.eshop"

server:
  tomcat:
    threads:
      max: 5
    max-connections: 10

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi,swaggerui,health,info

spring:
  cache:
    redis:
      time-to-live: 100S
    type: simple

